version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - ./.env
  web:
    image: iricshkin/yamdb_final:latest
    build: ../api_yamdb
    restart: always
    volumes:
      - static_value:/app/static/:rw
      - media_value:/app/madia/:rw
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_value:/var/html/static/:ro
      - media_value:/var/html/media/:ro
    depends_on:
      - web

volumes:
  static_value:
  media_value:
